export const GET_ALL_DEVICES_REQUEST = 'GET_ALL_DEVICES_REQUEST';
export const GET_ALL_DEVICES_SUCCESS = 'GET_ALL_DEVICES_SUCCESS';
export const GET_ALL_DEVICES_FAIL = 'GET_ALL_DEVICES_FAIL';
export const GET_ALL_DEVICES_RESET = 'GET_ALL_DEVICES_RESET';

export const ADD_DEVICE_REQUEST = 'ADD_DEVICE_REQUEST';
export const ADD_DEVICE_SUCCESS = 'ADD_DEVICE_SUCCESS';
export const ADD_DEVICE_FAIL = 'ADD_DEVICE_FAIL';
export const ADD_DEVICE_RESET = 'ADD_DEVICE_RESET';

export const UPDATE_DEVICE_REQUEST = 'UPDATE_DEVICE_REQUEST';
export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';
export const UPDATE_DEVICE_FAIL = 'UPDATE_DEVICE_FAIL';
export const UPDATE_DEVICE_RESET = 'UPDATE_DEVICE_RESET';

export const DELETE_DEVICE_REQUEST = 'DELETE_DEVICE_REQUEST';
export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS';
export const DELETE_DEVICE_FAIL = 'DELETE_DEVICE_FAIL';
export const DELETE_DEVICE_RESET = 'DELETE_DEVICE_RESET';

export const GET_DEVICE_REQUEST = 'GET_DEVICE_REQUEST';
export const GET_DEVICE_SUCCESS = 'GET_DEVICE_SUCCESS';
export const GET_DEVICE_FAIL = 'GET_DEVICE_FAIL';
export const GET_DEVICE_RESET = 'GET_DEVICE_RESET';
