export const GET_ALL_SESSIONS_REQUEST = 'GET_ALL_SESSIONS_REQUEST';
export const GET_ALL_SESSIONS_SUCCESS = 'GET_ALL_SESSIONS_SUCCESS';
export const GET_ALL_SESSIONS_FAIL = 'GET_ALL_SESSIONS_FAIL';
export const GET_ALL_SESSIONS_RESET = 'GET_ALL_SESSIONS_RESET';

export const ADD_SESSION_REQUEST = 'ADD_SESSION_REQUEST';
export const ADD_SESSION_SUCCESS = 'ADD_SESSION_SUCCESS';
export const ADD_SESSION_FAIL = 'ADD_SESSION_FAIL';
export const ADD_SESSION_RESET = 'ADD_SESSION_RESET';

export const UPDATE_SESSION_REQUEST = 'UPDATE_SESSION_REQUEST';
export const UPDATE_SESSION_SUCCESS = 'UPDATE_SESSION_SUCCESS';
export const UPDATE_SESSION_FAIL = 'UPDATE_SESSION_FAIL';
export const UPDATE_SESSION_RESET = 'UPDATE_SESSION_RESET';

export const DELETE_SESSION_REQUEST = 'DELETE_SESSION_REQUEST';
export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';
export const DELETE_SESSION_FAIL = 'DELETE_SESSION_FAIL';
export const DELETE_SESSION_RESET = 'DELETE_SESSION_RESET';

export const GET_SESSION_REQUEST = 'GET_SESSION_REQUEST';
export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS';
export const GET_SESSION_FAIL = 'GET_SESSION_FAIL';
export const GET_SESSION_RESET = 'GET_SESSION_RESET';
