export const GET_ALL_STORES_REQUEST = "GET_ALL_STORES_REQUEST";
export const GET_ALL_STORES_SUCCESS = "GET_ALL_STORES_SUCCESS";
export const GET_ALL_STORES_FAIL = "GET_ALL_STORES_FAIL";
export const GET_ALL_STORES_RESET = "GET_ALL_STORES_RESET";

export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST";
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS";
export const ADD_STORE_FAIL = "ADD_STORE_FAIL";
export const ADD_STORE_RESET = "ADD_STORE_RESET";

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";
export const UPDATE_STORE_RESET = "UPDATE_STORE_RESET";

export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAIL = "DELETE_STORE_FAIL";
export const DELETE_STORE_RESET = "DELETE_STORE_RESET";

export const GET_STORE_REQUEST = "GET_STORE_REQUEST";
export const GET_STORE_SUCCESS = "GET_STORE_SUCCESS";
export const GET_STORE_FAIL = "GET_STORE_FAIL";
export const GET_STORE_RESET = "GET_STORE_RESET";
